/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Provider;

import Business.EcoSystem;
import Business.Clinic.Clinic;
import Business.Enterprise.HospitalEnterprise;
import Business.Order.OrderItem;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.Vaccine.VaccineDetails;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samruddhamohire
 */
public class ViewInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInventoryJPanel
     */
    private JPanel workContainer;
    private EcoSystem business;
    private HospitalEnterprise hospitalEnterprise;
    private HospitalOrganization hospitalOrganization;
    private Clinic clinic;

    public ViewInventoryJPanel(JPanel workContainer, EcoSystem business, HospitalEnterprise hospitalEnterprise, HospitalOrganization hospitalOrganization) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
        this.hospitalEnterprise = hospitalEnterprise;
        this.hospitalOrganization = hospitalOrganization;
        populateOrderTable();

    }

    private void populateOrderTable() {

        int rowCount = tbldetails.getRowCount();
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tbldetails.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            defaulttabelmodel.removeRow(i);
        }
        for (Organization org : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof HospitalOrganization) {
                HospitalOrganization hospOrg = (HospitalOrganization) org;
                for (VaccineDetails product : hospOrg.getClinic().getVaccineInventoryClinic()) {
                    Object[] row = new Object[7];

                    row[0] = product;
                    row[1] = product.getVaccineDefinition().getVaccineName();
                    row[2] = product.getManufacturerName();
                    row[3] = product.getVaccineId();
                    row[4] = product.getBatchId();
                    row[5] = product.getAvailablity();
                    row[6] = product.getManufactureDate();
           

                    defaulttabelmodel.addRow(row);

                }
            }
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldetails = new javax.swing.JTable();
        brnref = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Inventory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 690, 40));

        tbldetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Brand", "Vaccine ID", "Batch ID", "Quantity", "Manufacture Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbldetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 930, 272));

        brnref.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        brnref.setForeground(new java.awt.Color(255, 255, 255));
        brnref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/MicrosoftTeams-image (2).png"))); // NOI18N
        brnref.setText("Refresh");
        brnref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnrefActionPerformed(evt);
            }
        });
        add(brnref, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 60, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, 930, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/warehouse.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 580, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void brnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnrefActionPerformed
        // TODO add your handling code here:
        populateOrderTable();
    }//GEN-LAST:event_brnrefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnref;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbldetails;
    // End of variables declaration//GEN-END:variables
}
